// CVM (Comissão de Valores Mobiliários) data access layer
//
// CVM provides official financial statements for all publicly-listed Brazilian companies
// via dados.cvm.gov.br. This module reads from the local cache generated by sync-cvm.ts.
//
// Data source: https://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DADOS/
// Encoding: UTF-8 / ISO-8859-1   Separator: semicolon (;)
// Monetary values: thousands of BRL (ESCALA_MOEDA = 'MIL') → divide by 1000 for BRL millions

import fs from 'fs'
import path from 'path'
import { getCVMRef } from '@/lib/data/cvm-ticker-map'
import type { SeededFundamental } from '@/lib/data/seeded-fundamentals'

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CVMAnnualData {
  year: number
  referenceDate: string  // YYYY-MM-DD (DT_FIM_EXERC)
  // Income Statement (BRL millions)
  revenue: number | null
  grossProfit: number | null
  ebit: number | null
  netIncome: number | null
  // Balance Sheet — Assets (BRL millions)
  totalAssets: number | null
  currentAssets: number | null
  cash: number | null
  noncurrentAssets: number | null
  // Balance Sheet — Liabilities + Equity (BRL millions)
  currentLiabilities: number | null
  noncurrentLiabilities: number | null
  shortTermDebt: number | null
  longTermDebt: number | null
  totalEquity: number | null
  // Cash Flow (BRL millions)
  operatingCF: number | null
  investingCF: number | null
  financingCF: number | null
}

export interface CVMQuarterlyData {
  year: number
  quarter: number  // 1-4
  referenceDate: string
  revenue: number | null
  ebit: number | null
  netIncome: number | null
  totalAssets: number | null
  totalEquity: number | null
}

export interface CVMCompanyData {
  cvmCode: string
  cnpj: string
  officialName: string
  updatedAt: string
  annual: CVMAnnualData[]   // sorted newest first
  quarterly: CVMQuarterlyData[]  // sorted newest first
}

export interface CVMCache {
  generatedAt: string
  companies: Record<string, CVMCompanyData>  // keyed by cvmCode
}

// ─── Cache loading ────────────────────────────────────────────────────────────

const CACHE_PATH = path.join(process.cwd(), 'lib', 'data', 'cvm-cache.json')

let _cache: CVMCache | null = null
let _cacheLoadedAt = 0
const CACHE_TTL_MS = 6 * 60 * 60 * 1000  // reload every 6h in long-running processes

function loadCache(): CVMCache | null {
  try {
    if (!fs.existsSync(CACHE_PATH)) return null
    const stat = fs.statSync(CACHE_PATH)
    if (_cache && (Date.now() - _cacheLoadedAt) < CACHE_TTL_MS) return _cache
    const raw = fs.readFileSync(CACHE_PATH, 'utf-8')
    _cache = JSON.parse(raw) as CVMCache
    _cacheLoadedAt = stat.mtimeMs
    return _cache
  } catch {
    return null
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function getCVMData(ticker: string): CVMCompanyData | null {
  const ref = getCVMRef(ticker)
  if (!ref) return null
  const cache = loadCache()
  if (!cache) return null
  return cache.companies[ref.cvmCode] ?? null
}

export function getCVMLatestAnnual(ticker: string): CVMAnnualData | null {
  return getCVMData(ticker)?.annual?.[0] ?? null
}

export function getCVMLatestQuarterly(ticker: string): CVMQuarterlyData | null {
  return getCVMData(ticker)?.quarterly?.[0] ?? null
}

// Returns whether CVM cache exists and has data
export function isCVMAvailable(): boolean {
  return loadCache() !== null
}

export function getCVMCacheInfo(): { generatedAt: string; companyCount: number } | null {
  const cache = loadCache()
  if (!cache) return null
  return {
    generatedAt: cache.generatedAt,
    companyCount: Object.keys(cache.companies).length,
  }
}

// ─── Overlay CVM data onto SeededFundamental ─────────────────────────────────
// Replaces financials with real CVM data while keeping model inputs (beta, DCF, etc.)
// from the seeded baseline. Safe to call even when CVM data is absent.

export function overlayCVMData(seeded: SeededFundamental): SeededFundamental {
  const annual = getCVMLatestAnnual(seeded.ticker)
  if (!annual) return seeded  // CVM not available — use seeded as-is

  const shares = seeded.sharesOutstanding  // still from seeded (Yahoo provides this too)

  // Compute derived values safely
  const ebitMargin =
    annual.revenue && annual.ebit ? annual.ebit / annual.revenue : seeded.ebitMargin

  const currentRatio =
    annual.currentAssets && annual.currentLiabilities && annual.currentLiabilities > 0
      ? annual.currentAssets / annual.currentLiabilities
      : seeded.currentRatio

  const totalDebt = (annual.shortTermDebt ?? 0) + (annual.longTermDebt ?? 0)
  const netDebt = totalDebt - (annual.cash ?? 0)

  const bvps =
    annual.totalEquity && shares > 0
      ? annual.totalEquity / shares
      : seeded.bvps

  const eps =
    annual.netIncome && shares > 0
      ? annual.netIncome / shares
      : seeded.eps

  // Build updated history (overlay most recent year in history array)
  const history = buildUpdatedHistory(seeded, annual)

  return {
    ...seeded,
    // Income
    revenue: annual.revenue ?? seeded.revenue,
    ebit: annual.ebit ?? seeded.ebit,
    ebitMargin,
    eps,
    // Balance Sheet
    bvps,
    currentRatio,
    totalDebt: totalDebt > 0 ? totalDebt : seeded.totalDebt,
    netDebt: totalDebt > 0 ? netDebt : seeded.netDebt,
    cash: annual.cash ?? seeded.cash,
    currentAssets: annual.currentAssets ?? seeded.currentAssets,
    currentLiabilities: annual.currentLiabilities ?? seeded.currentLiabilities,
    history,
  }
}

function buildUpdatedHistory(
  seeded: SeededFundamental,
  latest: CVMAnnualData,
): SeededFundamental['history'] {
  const hist = { ...seeded.history }
  const latestYear = latest.year

  // Replace/add the most recent year in history arrays
  const idx = hist.years.indexOf(latestYear)
  if (idx >= 0) {
    if (latest.revenue !== null) hist.revenue = replaceAt(hist.revenue, idx, latest.revenue)
    if (latest.ebit !== null) hist.ebit = replaceAt(hist.ebit, idx, latest.ebit)
    if (latest.netIncome !== null) hist.netIncome = replaceAt(hist.netIncome, idx, latest.netIncome)
    if (latest.totalEquity && seeded.sharesOutstanding > 0) {
      hist.bookValuePerShare = replaceAt(hist.bookValuePerShare, idx, latest.totalEquity / seeded.sharesOutstanding)
    }
  } else {
    // Append new year (only if it's after the last year in history)
    const lastYear = hist.years[hist.years.length - 1] ?? 0
    if (latestYear > lastYear) {
      hist.years = [...hist.years, latestYear]
      hist.revenue = [...hist.revenue, latest.revenue ?? seeded.revenue]
      hist.ebit = [...hist.ebit, latest.ebit ?? seeded.ebit]
      hist.netIncome = [...hist.netIncome, latest.netIncome ?? 0]
      hist.eps = [...hist.eps, seeded.eps]
      hist.roe = [...hist.roe, hist.roe[hist.roe.length - 1] ?? 0]
      hist.operatingMargin = [...hist.operatingMargin, latest.ebit && latest.revenue ? latest.ebit / latest.revenue : seeded.ebitMargin]
      hist.dividends = [...hist.dividends, hist.dividends[hist.dividends.length - 1] ?? 0]
      hist.bookValuePerShare = [...hist.bookValuePerShare, seeded.bvps]
    }
  }
  return hist
}

function replaceAt(arr: number[], idx: number, val: number): number[] {
  const copy = [...arr]
  copy[idx] = val
  return copy
}

// ─── CVM URL helpers (used by sync-cvm.ts) ────────────────────────────────────

export const CVM_BASE = 'https://dados.cvm.gov.br/dados/CIA_ABERTA'

export function dfpUrl(type: 'BPA' | 'BPP' | 'DRE' | 'DFC_MI', year: number): string {
  return `${CVM_BASE}/DOC/DFP/DADOS/dfp_cia_aberta_${type}_con_${year}.csv`
}

export function itrUrl(type: 'BPA' | 'BPP' | 'DRE', year: number): string {
  return `${CVM_BASE}/DOC/ITR/DADOS/itr_cia_aberta_${type}_con_${year}.csv`
}

export const CAD_URL = `${CVM_BASE}/CAD/DADOS/cad_cia_aberta.csv`

// Key account codes in CVM financial statements
export const ACCOUNT_CODES = {
  // BPA (Ativo)
  totalAssets:          '1',
  currentAssets:        '1.01',
  cash:                 '1.01.01',
  noncurrentAssets:     '1.02',
  // BPP (Passivo)
  currentLiabilities:   '2.01',
  shortTermDebt:        '2.01.04',
  noncurrentLiabilities:'2.02',
  longTermDebt:         '2.02.01',
  totalEquity:          '2.03',
  // DRE
  revenue:              '3.01',
  grossProfit:          '3.03',
  ebit:                 '3.05',
  netIncome:            '3.11',
  // DFC (Método Indireto)
  operatingCF:          '6.01',
  investingCF:          '6.02',
  financingCF:          '6.03',
} as const
